# Which is equivalent to
format = """
$python\
$directory\
$git_branch\
$sudo\
$cmd_duration\
$git_status\
$jobs\
$character"""

[git_status]
format="$all_status$ahead_behind"
conflicted = "ğŸ¥Š"
ahead = "ğŸ”¼"
behind = "ğŸ”½"
diverged = "ğŸ”€"
up_to_date = "[âœ“](green)"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "âœï¸"
staged = '[++\($count\)](green)'
renamed = "ğŸ“"
deleted = "ğŸ—‘"
